### ISSUE TITLE
Demo / UI admin interface / User experiences

### ISSUE THREAD

**Issue by wernerhp** [hn/seagate-blackarmor-nas#22]
Would you mind explaining a bit more about the use case of installing Debian and what the UI looks like/how you would use it.

**Comment by hn** [comment]
The script installs Debian via the normal installer and you can install all packages that the distribution offers. Since the BA NAS is an embedded system and quite old, you have to be very careful about the limited RAM. I've heard of people installing interfaces like [OMV](https://www.openmediavault.org/), but I've never done it myself and don't know if it works.
